### ISSUE TITLE
Is stepping possible with this?

### ISSUE THREAD

**Issue by dashw00d** [lara-zeus/quantity#11]
Hi,

I have a field where I need to increment in steps. I need to be able to specify the step amount like .1, .4, and .5 steps so I could get numbers like 1.1, 1.4, and 1.5. Is this possible?

Thanks!

**Comment by atmonshi** [comment]
not at the moment, I'll added as a feature request, and you're welcome to PR :)

**Comment by atmonshi** [comment]
better late than never :)

https://github.com/user-attachments/assets/6a21bf6a-5d42-43b4-9b41-89a473ca8c6d
