### ISSUE TITLE
isDisabled not working as expected

### ISSUE THREAD

**Issue by diegobas** [lara-zeus/quantity#18]
PHP: 8.3.8
Laravel: 11.30.0
Filament: 3.2.122 

"disabled" method does not work when used "reactively". I need to save the form and refresh the page to reflect the changes. When disabled, the color of the field goes to gray, but plus and minus buttons work.

```php
Quantity::make('minutes')
        ->hiddenLabel()
        ->required()
        ->default(0)
        ->minValue(0)
        ->maxValue(45)
        ->steps(15)
        ->disabled(fn (Get $get) => !$get('has_time_restriction'))
```

**Comment by atmonshi** [comment]
sorry for the delay.

this should be fixed with the last release, please confirm and if the issue still occur, feel free to reopen the issue.
